### ISSUE TITLE
Running Tests don't Complete

### ISSUE THREAD

**Issue by kaelrussell** [PSLCL/testing-framework#154]
Trying to run a test on the openDOF test harness results in the program hanging. Tests are continually being added to the "Running" field on the portal, but nothing shows up in the SQS queue and no EC2 instances are started.

**Comment by amauchley** [comment]
This isn't an issue on the framework not completing tests. The framework when executing dtfexec has to queue up all the test instances within a test id, it will appear as the console is stuck while doing this if there is a large amount of test instances needing to be queued, but as mentioned in the issue summary the test instances are being added as "runs" in the database.  This increases the "Running" field in the portal, but tests are queued to SQS until all of the test instances within a test id are inserted as "runs".  Once that is done, the console will print out the "queued test id" messages for all of the test instances.  After that AWS EC2 instances will start being launched.  This is just a formality that wasn't understood.  I'm closing the issue since it won't be fixed, where it isn't an issue at all.  The DTF just requires more time in order to fully complete the process.
