### ISSUE TITLE
Test Instances continue to increase even though no new modules have been promoted

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#155]
It appears that test instances continue to be created every single time the generators are executed even though there are no new modules that have been promoted.  I was under the impression that if a template was exactly the same the generated test instances would be compared to each other finding that they are equal and not create more test instances in the database.  This doesn't seem to be happening, it appears as if the generators just keep creating more and more instances.

**Comment by jwclark** [comment]
Possibly due to changes to the test?

**Comment by jwclark** [comment]
If a test is updated, then we don't need old test instances/runs. Can we prune those(only templates that are no longer generated by the test). That may not account for when a new test is added to the test component, as that will generate all new instances.

**Comment by jwclark** [comment]
This may also be caused by test components being merged with released components.

**Comment by clintjones** [comment]
Commits merged to dev branch on 7/26 benefit this issue. The issue was not precisely replicated, but a number of improvements have been added that reflect behaviors observed while testing. These improvements handle observed exceptions that have been able to cause generator runs to exit early, and NOT complete its intended database writing. In these cases, per this original issue report, re-running the generator would compute the full set of intended templates (and related test instances), and then write to the database the "not yet written" templates and test instances. Re-running the generator can thus be seen to add more test instances at each run, to the extent that the previous generator run had not completed its database writes.

**Comment by amauchley** [comment]
Closing this issue for now based on further discussion with engineers as described above in Clint's comments.
