### ISSUE TITLE
dtf properties has option for setting Security Group for all EC2 instances, but the runner doesn't use it

### ISSUE THREAD

**Issue by amauchley** [PSLCL/testing-framework#97]
The dtf.properties file allows you to define which security group to use for every EC2 instance that the runner initializes, but setting this option actually doesn't work.  Instead the runner will always use the default VPC Security Group.  The back-end code needs to be updated to allow you to set what Security Group you would like to use, if desired.  Otherwise if nothing is set for that option the runner should just use the default VPC security group.

**Comment by amauchley** [comment]
Also the Platform README should have instructions for what ports need to be opened for test instances and what property to change in the dtf.properties to use that security group.

**Comment by Chad-Adams** [comment]
Security Group Permissions have been removed from the properties file.  DTF currently only supports EC2-VPC  There is a regional "default VPC security group" which is automatically created by AWS.  The properties key this bug is written against allows a lab to override the AWS provided default SG.

A test script can also override this key to specify a custom SG for a given test.  The overriding SG's must be manually created outside of DTF.  Also note that which ever VPC security group is being used; aws provided, DTF override or script override, these must have the STAF ports allowed for incoming.  Typically ssh port 22 etc. might also be desired.
